# Generated by Django 3.1.3 on 2020-12-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioblog', '0002_post_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.CharField(max_length=2000),
        ),
    ]
