# Generated by Django 3.1.3 on 2020-12-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioblog', '0003_auto_20201203_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(verbose_name='%x'),
        ),
    ]
