# Generated by Django 3.1.3 on 2020-12-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioblog', '0004_auto_20201203_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(verbose_name='%Y-%m-%d'),
        ),
    ]
