# Generated by Django 3.1.3 on 2020-12-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioblog', '0006_auto_20201204_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato_text', models.CharField(max_length=2000)),
            ],
        ),
    ]
