# Generated by Django 3.1.3 on 2020-12-04 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioblog', '0007_about_contato'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contato',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contato_text',
            new_name='contact_text',
        ),
    ]
